name: CI Benchmark
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    strategy:
        matrix:
            os:
              - ubuntu-latest
              - macos-latest
              #- windows-latest
    name: Run Go benchmark example
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "stable"
      - name: Run benchmark
        run: go test -run='^$' -benchmem -bench=. ./... | tee "${RUNNER_OS}.txt"
          
      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result - wiki repo
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: ${{ runner.os }} Benchmark
          gh-repository: 'github.com/Omnikron13/splicearrays.wiki'
          github-token: ${{ github.token }}
          gh-pages-branch: 'master'
          benchmark-data-dir-path: "benchmarks"
          tool: 'go'
          output-file-path: ${{ runner.os }}.txt
          # Where the previous data file is stored - mutually exclusive with 'auto-push'
          #external-data-json-path: ./cache/benchmark-data.json
          auto-push: true
          # How this differs or combines to 'comment-on-alert', I have no idea...
          comment-always: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '125%'
          comment-on-alert: true

      #- name: Upload benchmark data
      #  run: |
      #    cd benchmark-data-repository
      #    git status
      #    git diff --staged
      #    cat "${RUNNER_OS}.txt"
      #    ls cache
      #    cat cache/benchmark-data.json
